import subprocess
from fastapi import FastAPI, UploadFile, File, Form, HTTPException
from fastapi.responses import FileResponse
import os
import uuid

app = FastAPI(title="F5-TTS Server")

@app.post("/api/tts")
async def generate_tts(
    text: str = Form(...),
    ref_text: str = Form(""),
    ref_audio: UploadFile = File(None)
):
    temp_dir = f"/tmp/{uuid.uuid4()}"
    os.makedirs(temp_dir, exist_ok=True)
    
    ref_path = ""
    if ref_audio and ref_audio.filename:
        ref_path = os.path.join(temp_dir, ref_audio.filename)
        with open(ref_path, "wb") as f:
            f.write(await ref_audio.read())
    else:
        # Fallback to an empty reference if not provided (might cause issues with zero-shot cloning, but F5-TTS requires it)
        raise HTTPException(status_code=400, detail="Reference audio is required for F5-TTS")
            
    output_path = os.path.join(temp_dir, "output.wav")
    
    # Run the F5-TTS CLI
    cmd = [
        "f5-tts_infer-cli",
        "--model", "F5-TTS", # Base model architecture
        "--ckpt_file", "/workspace/model/f5_tts_indo_v2.pt", # Our finetuned weights
        "--gen_text", text,
        "--ref_audio", ref_path,
        "--ref_text", ref_text,
        "--output_dir", temp_dir
    ]
    
    print(f"Running command: {' '.join(cmd)}")
    try:
        subprocess.run(cmd, check=True)
        
        # The CLI saves as 'out.wav' or named after gen_text. Let's find it.
        generated_files = [f for f in os.listdir(temp_dir) if f.endswith('.wav') and f != os.path.basename(ref_path)]
        
        if not generated_files:
            raise HTTPException(status_code=500, detail="No output audio generated by F5-TTS")
            
        final_output = os.path.join(temp_dir, generated_files[0])
        return FileResponse(final_output, media_type="audio/wav")
        
    except subprocess.CalledProcessError as e:
        print(f"Error executing F5-TTS: {e}")
        raise HTTPException(status_code=500, detail="Error generating TTS audio")
