services:
  backend:
    image: ghcr.io/tarisrizki/lambadaclips-backend:master
    container_name: lambadaclips-backend
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - /app/__pycache__
      - ./output:/app/output
    restart: unless-stopped


  renderer:
    image: ghcr.io/tarisrizki/lambadaclips-renderer:master
    container_name: lambadaclips-renderer
    ports:
      - "3100:3100"
    volumes:
      - ./output:/output
    environment:
      - REMOTION_BUNDLE_PATH=/app/remotion
      - OUTPUT_DIR=/output
      - PORT=3100
    restart: unless-stopped
    depends_on:
      - backend
